/**
 * Hooks Index Export

































































































































































































































































































































}  );    </div>      </div>        </p>          {message.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}        <p className={`text-xs mt-1 ${isUser ? 'text-emerald-200' : 'text-slate-500'}`}>        <p className="text-sm leading-relaxed whitespace-pre-wrap">{message.content}</p>        )}          </div>            <span className="text-xs font-medium text-emerald-400">Rafiki</span>            <span className="text-sm">🤖</span>          <div className="flex items-center gap-2 mb-1">        {!isUser && (      `}>          : 'bg-slate-700/50 text-slate-100 rounded-bl-md'}          ? 'bg-emerald-600 text-white rounded-br-md'         ${isUser         max-w-[80%] md:max-w-[60%] px-4 py-3 rounded-2xl      <div className={`    <div className={`flex ${isUser ? 'justify-end' : 'justify-start'}`}>  return (    const isUser = message.role === 'user';function MessageBubble({ message }: { message: Message }) {// Message Bubble Component}  );    </div>      </div>        </div>          </div>            </p>                : 'Gusa kipaza sauti kuongea au andika ujumbe wako'}                ? 'Tap the microphone to speak or type your message'              {language === 'en-KE'             <p className="mt-2 text-center text-xs text-slate-500">            {/* Mobile hint */}                        </form>              </button>                </svg>                  <path strokeLinecap="round" strokeLinejoin="round" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />                <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>              >                className="p-4 rounded-full bg-emerald-500 hover:bg-emerald-600 text-white disabled:opacity-50 disabled:hover:bg-emerald-500 transition-colors"                disabled={!textInput.trim() || isProcessing || isSpeaking || isListening}                type="submit"              <button              {/* Send Button */}              />                className="flex-1 px-4 py-3 bg-slate-700/50 border border-slate-600/50 rounded-xl text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-emerald-500/50 disabled:opacity-50"                disabled={isProcessing || isSpeaking || isListening}                placeholder={language === 'en-KE' ? 'Type your message...' : 'Andika ujumbe wako...'}                onKeyDown={handleKeyDown}                onChange={(e) => setTextInput(e.target.value)}                value={textInput}                type="text"              <input              {/* Text Input */}              )}                </button>                  </svg>                    <path strokeLinecap="round" strokeLinejoin="round" d="M9 10a1 1 0 011-1h4a1 1 0 011 1v4a1 1 0 01-1 1h-4a1 1 0 01-1-1v-4z" />                    <path strokeLinecap="round" strokeLinejoin="round" d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />                  <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>                >                  title="Stop speaking"                  className="p-4 rounded-full bg-orange-500 hover:bg-orange-600 text-white transition-colors"                  onClick={stopSpeaking}                  type="button"                <button              {isSpeaking && (              {/* Stop Speaking Button */}              </button>                )}                  />                    style={{ transform: `scale(${1 + audioLevel / 128})` }}                    className="absolute inset-0 rounded-full bg-red-400 animate-ping opacity-30"                  <span                 {isListening && (                {/* Audio level indicator */}                                )}                  </svg>                    <path strokeLinecap="round" strokeLinejoin="round" d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" />                  <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>                ) : (                  </svg>                    <rect x="6" y="6" width="12" height="12" rx="2" fill="currentColor" />                  <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">                {isListening ? (              >                `}                    : 'bg-emerald-500 hover:bg-emerald-600 text-white'}                    ? 'bg-red-500 hover:bg-red-600 text-white animate-pulse'                   ${isListening                   relative p-4 rounded-full transition-all duration-300 disabled:opacity-50                className={`                disabled={isProcessing || isSpeaking}                onClick={toggleListening}                type="button"              <button              {/* Microphone Button */}            <form onSubmit={handleSubmit} className="flex items-center gap-3">          <div className="p-4 bg-slate-800/30 border-t border-slate-700/30">          {/* Input Area */}          </div>            <div ref={messagesEndRef} />                        )}              </div>                <span className="text-sm">Rafiki is typing...</span>                </div>                  <span className="w-2 h-2 bg-emerald-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />                  <span className="w-2 h-2 bg-emerald-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />                  <span className="w-2 h-2 bg-emerald-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />                <div className="flex gap-1">              <div className="flex items-center gap-2 text-slate-400">            {isProcessing && (            {/* Typing indicator */}                        ))}              <MessageBubble key={message.id} message={message} />            {messages.map((message) => (                        )}              </div>                </p>                    : 'Msaidizi wako wa AI kwa huduma za serikali ya Kenya. Gusa kipaza sauti kuongea au andika swali lako hapa chini.'}                    ? 'Your AI assistant for Kenyan government services. Tap the microphone to speak or type your question below.'                  {language === 'en-KE'                 <p className="text-slate-400 max-w-md">                </h2>                  {language === 'en-KE' ? 'Hello! I\'m Rafiki' : 'Habari! Mimi ni Rafiki'}                <h2 className="text-xl font-semibold text-white mb-2">                <div className="text-6xl mb-4">👋</div>              <div className="flex flex-col items-center justify-center h-full text-center">            {messages.length === 0 && (          <div className="flex-1 overflow-y-auto p-4 space-y-4">          {/* Messages */}        <div className="flex-1 flex flex-col">        {/* Chat Area */}        </div>          </div>            ))}              </button>                <span className="text-xs">{action.label}</span>                <span>{action.icon}</span>              >                className="flex items-center gap-2 px-3 py-2 bg-slate-700/30 hover:bg-slate-600/30 rounded-lg text-sm text-slate-300 disabled:opacity-50 transition-colors"                disabled={state !== 'idle'}                onClick={() => sendMessage(`I need help with ${action.label}`)}                key={action.label}              <button            ].map(action => (              { label: 'Good Conduct', icon: '📋' },              { label: 'Driving License', icon: '🚗' },              { label: 'National ID', icon: '🪪' },              { label: 'Passport', icon: '🛂' },            {[          <div className="mt-6 grid grid-cols-2 gap-2 w-full max-w-xs">          {/* Quick Actions */}                    )}            </div>              <p className="text-sm text-white italic">"{transcript}"</p>              <p className="text-xs text-slate-400 mb-1">Hearing:</p>            <div className="mt-6 p-3 bg-slate-700/30 rounded-lg w-full max-w-xs">          {isListening && transcript && (          {/* Live transcript */}                    </div>            </div>              {state === 'idle' && '✨ Ready'}              {state === 'speaking' && '💬 Speaking...'}              {state === 'processing' && '🧠 Thinking...'}              {state === 'listening' && '🎤 Listening...'}            `}>              ${state === 'idle' ? 'bg-slate-500/20 text-slate-400' : ''}              ${state === 'speaking' ? 'bg-emerald-500/20 text-emerald-400' : ''}              ${state === 'processing' ? 'bg-purple-500/20 text-purple-400' : ''}              ${state === 'listening' ? 'bg-blue-500/20 text-blue-400' : ''}              absolute -bottom-2 left-1/2 -translate-x-1/2 px-3 py-1 rounded-full text-xs font-medium            <div className={`            {/* State indicator */}                        />              } : undefined}                viseme: 'neutral',                isSpeaking: false,                amplitude: audioLevel / 128,              audioData={isListening ? {              showWaveform={state === 'listening' || state === 'speaking'}              showParticles={true}              size={200}              state={getAvatarState()}            <RafikiImageAvatar          <div className="relative">        <div className="hidden md:flex w-80 flex-col items-center justify-center p-6 bg-slate-800/30 border-r border-slate-700/30">        {/* Avatar Panel */}      <div className="flex flex-1 overflow-hidden">      {/* Main Content */}      </header>        </div>          )}            </button>              Logout            >              className="px-3 py-1.5 text-xs font-medium rounded-lg bg-red-600/20 text-red-400 hover:bg-red-600/30 transition-colors"              onClick={onLogout}            <button          {onLogout && (                    </button>            New Chat          >            className="px-3 py-1.5 text-xs font-medium rounded-lg bg-emerald-600/20 text-emerald-400 hover:bg-emerald-600/30 transition-colors"            onClick={clearConversation}          <button          {/* New Chat */}                    </button>            {language === 'en-KE' ? '🇬🇧 English' : '🇰🇪 Kiswahili'}          >            className="px-3 py-1.5 text-xs font-medium rounded-lg bg-slate-700/50 text-slate-300 hover:bg-slate-600/50 transition-colors"            onClick={() => setLanguage(lang => lang === 'en-KE' ? 'sw-KE' : 'en-KE')}          <button          {/* Language Toggle */}        <div className="flex items-center gap-3">                </div>          </div>            <p className="text-xs text-slate-400">Government Services Assistant</p>            <h1 className="text-lg font-bold text-white">Rafiki AI</h1>          <div>          <span className="text-2xl">🇰🇪</span>        <div className="flex items-center gap-3">      <header className="flex items-center justify-between px-4 py-3 bg-slate-800/50 border-b border-slate-700/50">      {/* Header */}    <div className="flex flex-col h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900">  return (  };    }      handleSubmit(e);      e.preventDefault();    if (e.key === 'Enter' && !e.shiftKey) {  const handleKeyDown = (e: React.KeyboardEvent) => {  // Handle keyboard shortcuts  };    await sendMessage(input);    setTextInput('');    const input = textInput;        if (!textInput.trim()) return;    e.preventDefault();  const handleSubmit = async (e: React.FormEvent) => {  // Handle text input submit  };    }      default: return 'idle';      case 'speaking': return 'speaking';      case 'processing': return 'thinking';      case 'listening': return 'listening';    switch (state) {  const getAvatarState = () => {  // Map state to avatar state  }, [messages]);    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });  useEffect(() => {  // Auto-scroll to latest message  });    },      console.error('Conversation error:', error);    onError: (error) => {    autoSpeak: true,    language,  } = useVoiceConversation({    isProcessing,    isSpeaking,    clearConversation,    stopSpeaking,    sendMessage,    toggleListening,    stopListening,    startListening,    audioLevel,    transcript,    isListening,    messages,    state,  const {  const messagesEndRef = useRef<HTMLDivElement>(null);  const [language, setLanguage] = useState<'en-KE' | 'sw-KE'>('en-KE');  const [textInput, setTextInput] = useState('');export default function ConversationalChat({ onLogout }: ConversationalChatProps) {}  onLogout?: () => void;interface ConversationalChatProps {import { RafikiImageAvatar } from '../avatar';import { useVoiceConversation, type Message } from '../../hooks/useVoiceConversation';import { useState, useRef, useEffect } from 'react'; */ * Voice-enabled chat interface with Rafiki AI assistant * All animation and interaction hooks for Rafiki Avatar
 */

// Core animation hooks
export { useAudioAnalyzer } from './useAudioAnalyzer';
export { useBlinking } from './useBlinking';
export { useMicroMovements } from './useMicroMovements';

// Enhanced animation hooks
export { useBreathing } from './useBreathing';
export { useEyeTracking } from './useEyeTracking';
export { useEmotions, type Emotion, type FacialExpression } from './useEmotions';
export { usePhonemeAnalyzer } from './usePhonemeAnalyzer';
export { useSpeechSynthesis } from './useSpeechSynthesis';
export { useIdleAnimation } from './useIdleAnimation';

// Voice conversation hook
export { 
  useVoiceConversation, 
  type ConversationState, 
  type Message,
  type UseVoiceConversationOptions 
} from './useVoiceConversation';

// SadTalker integration for realistic lip-sync
export { 
  useSadTalker, 
  type SadTalkerJob, 
  type SadTalkerOptions,
  type Avatar,
  type AnimationSettings 
} from './useSadTalker';
